set classpath=../../bin;../../lib/ext/javassist.jar;../../lib/junit.jar
@echo off


java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estA1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estA2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estB1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estB2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estC1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estC2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estD1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estD2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estE1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estE2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estF1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estF2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estG1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estG2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estG3 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estH1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estH2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estI1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estI2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estJ1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estJ2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estK1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estK2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estL1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estL2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estM1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estM2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estN1 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estN2 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estN3 simple
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estN4 simple

java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estA1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estA2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estB1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estB2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estC1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estC2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estD1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estD2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estE1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estE2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estF1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estF2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estG1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estG2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estG3 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estH1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estH2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estI1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estI2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estJ1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estJ2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estK1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estK2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estL1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estL2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estM1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estM2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estN1 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estN2 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estN3 complex
java org.neodatis.odb.test.acid.TestStopEngineWithoutCommit t1estN4 complex

rem java org.neodatis.odb.test.refactoring.Result end
